Added build arg to instarr BDB and OSM dev plugins
kartoza/docker-geogig pull request #8
Opened 2016-12-02 16:48 UTC by luipir

2016-12-03 20:12 UTC, timlinux requested changes

2016-12-03 20:12 UTC, timlinux commented on README.md
> +**BDBPLUGIN** build arg to be se set to BDB to install Berkley DB dev geogig plugin
se set -> set

2016-12-03 20:12 UTC, timlinux commented on README.md
> +**OSMPLUGIN** build arg to be se set to OSM to install OSM dev geogig plugin
se set -> set

2016-12-03 20:13 UTC, timlinux commented
Thanks for the patch @luipir !

2016-12-14 15:15 UTC, luipir commented
done changes to readme

2016-12-17 09:34 UTC, merged